[package]
name = "andi"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.2"
quick-xml = { version = "0.38.3", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
